name: Multiarch build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

  workflow_dispatch:

env:
  IMAGE_NAME: jamulus
  IMAGE_TAG: v3.10.0
  IMAGE_REGISTRY: docker.io
  IMAGE_NAMESPACE: email4tong

jobs:
  build:
    name: Build and push multi-arch image
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        
      - name: set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DH_USER }}
          password: ${{ secrets.DH_KEY }}

      - name: build and push images
        run: |
          docker buildx build --push \
            --tag ${{env.IMAGE_NAMESPACE }}/${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}} \
            --platform linux/amd64,linux/arm64 .